-- FRANCISCO JAVIER BLÁZQUEZ MARTÍNEZ  ~  frblazqu@ucm.es
-- MANUEL ORTEGA SALVADOR              ~  manuor01@ucm.es
--
--   Doble grado Ingeniería informática - Matemáticas
--	 Universidad Complutense de Madrid.

CREATE TABLESPACE EMPRESADG04 DATAFILE 'D:\oracle\EMPRESADG04' SIZE
100M AUTOEXTEND OFF;

CREATE USER DG04 IDENTIFIED BY DG04PWD DEFAULT TABLESPACE EMPRESADG04
TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON EMPRESADG04;

GRANT CREATE SESSION, CREATE TABLE, DELETE ANY TABLE, SELECT ANY
DICTIONARY, CREATE ANY SEQUENCE TO DG04;


-- Respuesta del servidor:
/*
TABLESPACE EMPRESADG04 creado.
User DG04 creado.
Grant correcto.
*/
